### ISSUE TITLE
UI of steam sieve doesn't open

### ISSUE THREAD

**Issue by herzblut** [EmosewaPixel/GregBlockUtilities#8]
I'm currently playing GregBlock version 2.2.1 with GregBlockUtilities in version 1.2.2. 

I'm not able to open the UI of the steam sieve. Afer placing it and doing a right click on it, the debug log contains the following error:
```
java.util.concurrent.ExecutionException: java.lang.NoSuchFieldError: workableHandler
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_112]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_112]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: java.lang.NoSuchFieldError: workableHandler
	at gregblockutils.Machines.SteamSieve.createUI(SteamSieve.java:49) ~[SteamSieve.class:?]
	at gregtech.api.metatileentity.MetaTileEntityUIFactory.createUITemplate(MetaTileEntityUIFactory.java:30) ~[MetaTileEntityUIFactory.class:?]
	at gregtech.api.metatileentity.MetaTileEntityUIFactory.createUITemplate(MetaTileEntityUIFactory.java:16) ~[MetaTileEntityUIFactory.class:?]
	at gregtech.api.gui.UIFactory.openUI(UIFactory.java:39) ~[UIFactory.class:?]
	at gregtech.api.metatileentity.MetaTileEntity.onRightClick(MetaTileEntity.java:307) ~[MetaTileEntity.class:?]
	at gregtech.api.metatileentity.MetaTileEntity.onCoverRightClick(MetaTileEntity.java:285) ~[MetaTileEntity.class:?]
	at gregtech.api.block.machines.BlockMachine.func_180639_a(BlockMachine.java:278) ~[BlockMachine.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:449) ~[or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:741) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[ma.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[ma.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_112]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_112]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more```

**Comment by ghost** [comment]
This mod is abandoned

**Comment by ZeroSkill1** [comment]
Why is this mod abandoned?

**Comment by OminousPlayz** [comment]
I found a work-around the UI. You just have to use a hopper, feed in the mesh and whatever you want to be sieved, and then hopper them out from the duct hatch side. Make sure your vent is open so the siever works. Hope this works.
